AWSTemplateFormatVersion: '2019-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API de Envios

Resources:
    Envios:
        Type: AWS::Serverless::Function
        Properties:
          Handler: index.handler
          Runtime: nodejs10.x
          Timeout: 60
          Events:
              CrearEnvio:
                  Type: Api
                  Properties:
                        Path: /envios
                        Method: post
              VerEnvios:
                  Type: Api
                  Properties:
                        Path: /envios/{idEnvio}
                        Method: get
              VerPendiente:
                  Type: Api
                  Properties:
                        Path: /envios/pendientes
                        Method: get
              CancelarPendiente:
                  Type: Api
                  Properties:
                        Path: /envios/{idEnvio}/entregado
                        Method: post
